services:
  app:
    container_name: 'alertNature'
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: 'alertNotification'
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: ${APP_BD}
      POSTGRES_USER: ${APP_BD_USER}
      POSTGRES_PASSWORD: ${APP_BD_PASS}
    ports:
      - '5432:5432'
    volumes:
      - bePrepared_postgres:/var/lib/postgresql/data
    networks:
      - bePrepared_postgres_net
volumes:
  bePrepared_postgres:
    name: 'alertNotification'
networks:
  bePrepared_postgres_net:
    name: 'alertNotification_net'
    driver: bridge