spring:
  application:
    name: 'bePrepared'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${APP_BD_URL}
    username: ${APP_BD_USER}
    password: ${APP_BD_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USER}
    password: ${SPRING_MAIL_PASS}
    sender-name: ${SPRING_MAIL_SENDER_NAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  secret:
    key: ${APP_SECRET_KEY}
    expiration-time: ${APP_SECRET_EXPIRATION}
  services:
    sms:
      account-sid: ${APP_SERVICES_SMS_ACCOUNT_SID}
      auth-token: ${APP_SERVICES_SMS_AUTH_TOKEN}
      number-from: ${APP_SERVICES_SMS_NUMBER_FROM}
logging:
  file:
    name: bePrepared.log
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method