spring:
  application:
    name: 'bePrepared'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${APP.BD.URL}
    username: ${APP.BD.USER}
    password: ${APP.BD.PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${SPRING.MAIL.HOST}
    port: ${SPRING.MAIL.PORT}
    username: ${SPRING.MAIL.USER}
    password: ${SPRING.MAIL.PASS}
    sender-name: ${SPRING.MAIL.SENDER-NAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  secret:
    key: ${APP.SECRET.KEY}
    expiration-time: ${APP.SECRET.EXPIRATION}
  services:
    sms:
      account-sid: ${APP.SERVICES.SMS.ACCOUNT-SID}
      auth-token: ${APP.SERVICES.SMS.AUTH-TOKEN}
      number-from: ${APP.SERVICES.SMS.NUMBER-FROM}
logging:
  file:
    name: bePrepared.log
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method